# Generated by Django 5.2 on 2025-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/default_car.jpg', upload_to='cars/'),
        ),
    ]
